SELECT * 
FROM (
	SELECT 
	  TGFFIN.NUFIN, 
	  TGFFIN.NUNOTA, 
	  TGFFIN.CODPARC, 
	  TO_CHAR(TGFFIN.DTNEG, 'YYYY-MM-DD') AS DTNEG, 
	  TO_CHAR(TGFFIN.DTVENC, 'YYYY-MM-DD') AS DTVENC, 
	  TGFFIN.DESDOBRAMENTO, 
	  TGFFIN.VLRDESDOB,
	  TGFFIN.NOSSONUM,
	  TGFFIN.LINHADIGITAVEL,
	  TGFFIN.CODIGOBARRA,
	  TGFFIN.EMVPIX
	  FROM TGFPAR 
	    INNER JOIN TGFFIN ON (TGFPAR.CODPARC = TGFFIN.CODPARC)
	    LEFT JOIN TGFCAB ON (TGFCAB.NUNOTA = TGFFIN.NUNOTA)
	 WHERE TGFFIN.RECDESP = 1
	   AND TGFFIN.CODTIPTIT = 4
	   AND TGFFIN.PROVISAO = 'N' 
	   AND TGFFIN.DHBAIXA IS NULL
	   {{{filtro}}}
	 )